apiVersion: v1
kind: Service
metadata:
  name: hospitalrun-backend
spec:
  selector:
    app: hospitalrun-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP