apiVersion: v1
kind: Service
metadata:
  name: hospitalrun-frontend
spec:
  selector:
    app: hospitalrun-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer