apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospitalrun-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospitalrun-frontend
  template:
    metadata:
      labels:
        app: hospitalrun-frontend
    spec:
      containers:
        - name: frontend
          image: 
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-volume
              mountPath: ..
      volumes:
        - name: frontend-volume
          emptyDir: {}

