apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospitalrun-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospitalrun-mongo
  template:
    metadata:
      labels:
        app: hospitalrun-mongo
    spec:
      containers:
        - name: mongo
          image: 
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "Serafino"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "adminpass"
          ports:
            - containerPort: 27017