apiVersion: v1
kind: Service
metadata:
  name: hospitalrun-mongo
spec:
  selector:
    app: hospitalrun-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP