apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hospitalrun-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: hospitalrun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hospitalrun-frontend
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: hospitalrun-backend
                port:
                  number: 3000